// <auto-generated />
using System;
using BookQuotes.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookQuotes.Api.Migrations
{
    [DbContext(typeof(BookQuotesDbContext))]
    partial class BookQuotesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("BookQuotes.Api.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Elena Berg",
                            PublicationDate = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Quiet Library"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Daniel Lund",
                            PublicationDate = new DateTime(2021, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Maps of Morning"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mira Holm",
                            PublicationDate = new DateTime(2019, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last Bookmark"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Samuel Reed",
                            PublicationDate = new DateTime(2022, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Under Northern Skies"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Nora Ellis",
                            PublicationDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Garden of Pages"
                        });
                });

            modelBuilder.Entity("BookQuotes.Api.Domain.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Anonymous",
                            Text = "Every good story leaves a small light on after the final page."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Anonymous",
                            Text = "A quiet chapter can still move a whole life forward."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Anonymous",
                            Text = "Books give ordinary afternoons somewhere new to go."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Anonymous",
                            Text = "The best journeys often begin before the first step is taken."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Anonymous",
                            Text = "A favorite quote is a thought worth returning to."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
